#!/bin/bash

RIM_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

__rim_template_path=${RIM_HOME}/templates
__rim_ruby="/usr/bin/env ruby"
__rim_as_string_ext="active_support/core_ext/string"

function rim() {
  next_token=$1; shift
  case "$next_token" in
    (m|mig|migration)
      local migration_type=$1
      local table_name=$2
      __rim_template migrations $migration_type $table_name
      ;;
    (t|tdd|test)
      local framework=$1
      local tested_file=$2
      __rim_template tdd $framework $tested_file
      ;;
  esac
}

rim "$@"
exit 0
